Features/footer
aggenov/ice-cream pull request #12
Opened 2023-01-20 16:38 UTC by MariySemenenko

2023-01-20 17:17 UTC, aggenov requested changes
весь контент должен находиться внутри  div container

2023-01-20 20:53 UTC, aggenov requested changes
background-color: --background-main-color;
 должно быть так
background-color: var(--background-main-color);

padding-top нужно задавать не на .footer_text а на .footer_text

2023-01-21 11:34 UTC, aggenov approved these changes

2023-01-21 11:38 UTC, koreniak approved these changes

2023-01-21 11:38 UTC, aggenov approved these changes

2023-01-21 12:09 UTC, merged