new
aggenov/ice-cream pull request #14
Opened 2023-01-20 17:08 UTC by DimaGoculenko

2023-01-20 17:25 UTC, aggenov requested changes
переменные возьми из root

2023-01-20 18:06 UTC, aggenov reviewed
додаю

2023-01-20 19:04 UTC, koreniak approved these changes

2023-01-21 09:50 UTC, aggenov approved these changes
ok

2023-01-21 09:51 UTC, merged

2023-01-21 10:10 UTC, aggenov reviewed
в названии файла есть недопустимые символы - Git не дает ветку подключить

src/images/svg/optim-svg/>>>ep_arrow-right-bold-->>>.svg