Gallery (slider)
aggenov/ice-cream pull request #15
Opened 2023-01-20 17:48 UTC by Igor-v-Bogdanov

2023-01-20 17:53 UTC, MMAKS999 commented
Зробили тільки слайдер?

2023-01-20 18:04 UTC, aggenov reviewed
добавь еще класс для секции

2023-01-20 19:04 UTC, koreniak approved these changes

2023-01-20 19:09 UTC, MMAKS999 approved these changes
класно

2023-01-20 23:18 UTC, MMAKS999 approved these changes

2023-01-21 09:27 UTC, aggenov approved these changes

2023-01-21 10:40 UTC, aggenov requested changes
нужно перезадать имя Swiper на другое Js не дает решить конфликт

2023-01-21 10:40 UTC, aggenov commented on src/index.html
> +      var swiper = new Swiper('.mySwiper', {
Swiper уже есть - может изменить в твоем блоке на Swiper1 например

2023-01-21 11:33 UTC, Igor-v-Bogdanov reviewed
По-моему закончил всю секцию.

2023-01-21 12:12 UTC, aggenov approved these changes
остался только вопрос с именем MySwiper

2023-01-21 14:14 UTC, aggenov approved these changes

2023-01-21 14:14 UTC, aggenov commented on src/index.html
> +    <link href="./images/ico-favicon.png" rel="apple-touch-icon" />
линк нужно ставить перед двумя последними двумя строчками в head
это строчки сборщика

2023-01-21 15:00 UTC, koreniak approved these changes

2023-01-21 15:00 UTC, koreniak approved these changes

2023-01-21 15:10 UTC, Igor-v-Bogdanov reviewed
Переименовал в index.html и gallery.html - теперь не должно конфликтовать. Оказывается нам Влад на последнем занятии это показывал!

2023-01-21 17:44 UTC, aggenov approved these changes

2023-01-21 17:44 UTC, merged